name: GN
channels:
  - conda-forge
  - intel
  - defaults
dependencies:
  - anyio=3.1.0
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=3.3.0
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.7
  - cycler=0.10.0
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.10.4
  - idna=2.10
  - importlib-metadata=4.3.0
  - ipykernel=5.5.5
  - ipython=7.23.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.8.0
  - jupyterlab=3.0.16
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.5.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.1.0
  - libdeflate=1.7
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.3.0
  - libwebp-base=1.2.0
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - nbclassic=0.3.1
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandoc=2.13
  - pandocfilters=1.4.2
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.2
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.18
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyzmq=22.1.0
  - readline=8.1
  - requests=2.25.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - sniffio=1.2.0
  - sqlite=3.35.5
  - terminado=0.10.0
  - testpath=0.5.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.61.0
  - traitlets=5.0.5
  - urllib3=1.26.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - absl-py==0.12.0
    - astunparse==1.6.3
    - cachetools==4.2.2
    - dill==0.3.3
    - flatbuffers==1.12
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.30.1
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - googleapis-common-protos==1.53.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - importlib-resources==5.1.4
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - promise==2.3
    - protobuf==3.17.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - six==1.15.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.1
    - tensorflow-addons==0.13.0
    - tensorflow-datasets==4.3.0
    - tensorflow-estimator==2.4.0
    - tensorflow-metadata==1.0.0
    - termcolor==1.1.0
    - typeguard==2.12.0
    - typing-extensions==3.7.4.3
    - werkzeug==2.0.1
    - wrapt==1.12.1
